import Head from "next/head";
import styles from "../styles/Home.module.sass";
import Header from "../components/Header";
import { Element } from "react-scroll";
import HomeComponent from "../components/HomeComponent";
import About from "../components/About";
import Security from "../components/Security";
import Services from "../components/Services";
import Contact from "../components/Contact";
import Footer from "../components/Footer";
import { useEffect, useState } from "react";

export default function Home() {
	const [offset, setOffset] = useState(0);

	function logOffset() {
		setOffset(window.scrollY);
	}

	useEffect(() => {
		if (typeof window !== "undefined") {
			window.addEventListener("scroll", logOffset);
		}

		return () => {
			window.removeEventListener("scroll", logOffset);
		};
	});

	return (
		<>
			<Head>
				<title>Responsive Delivery Website</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />

				{/* boxicons */}
				<link
					rel="stylesheet"
					href="https://cdn.jsdelivr.net/npm/boxicons@latest/css/boxicons.min.css"
				/>
			</Head>

			<Header />

			{/* main */}
			<main className={styles.main}>
				<Element name="home">
					<HomeComponent />
				</Element>
				<Element name="about">
					<About />
					<Security />
				</Element>
				<Element name="services">
					<Services />
				</Element>
				<Element name="contact">
					<Contact />
				</Element>
			</main>

			<Footer />

			<a
				href="#"
				className={`scrollup ${
					offset > 100 ? "show-scroll" : ""
				}`}
			>
				<i className="bx bx-up-arrow-alt scrollup__icon"></i>
			</a>
		</>
	);
}
